#include "PgDatabase.h"
#include "GraphingErrorCode.h"
#include <QDebug>
#include <QProcessEnvironment>
#include <QRandomGenerator>
#include <QSqlError>
#include <QSqlQuery>
#include <QVariant>

namespace {
    const char* kConnectionName = "graphing_server_pg_database";
    const char* kPasswordResetCleanupJobName = "graphing_server_password_reset_cleanup";
    const char* kPasswordResetCleanupJobSchedule = "0 * * * *";
    const char* kPasswordResetCleanupJobCommand = "SELECT public.cleanup_expired_password_reset_tokens_job()";
}

PgDatabase::PgDatabase() {
    if (QSqlDatabase::contains(kConnectionName)) {
        this->database = QSqlDatabase::database(kConnectionName);
    } else {
        this->database = QSqlDatabase::addDatabase("QPSQL", kConnectionName);
    }
}

QString PgDatabase::getEnvValue(const char* primaryName, const char* fallbackName) const {
    QString value = qEnvironmentVariable(primaryName);
    if (!value.isEmpty()) {
        return value;
    }

    if (fallbackName) {
        value = qEnvironmentVariable(fallbackName);
        if (!value.isEmpty()) {
            return value;
        }
    }

    return "";
}

FailableOperationResult PgDatabase::ensurePgCrypto() {
    QSqlQuery query(this->database);
    if (query.exec("CREATE EXTENSION IF NOT EXISTS pgcrypto")) {
        return FailableOperationResult::ok();
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Cannot enable pgcrypto: %1").arg(query.lastError().text())
    );
}

FailableOperationResult PgDatabase::ensurePasswordResetSchema() {
    QSqlQuery query(this->database);
    if (query.exec(
        "CREATE TABLE IF NOT EXISTS public.password_reset_tokens ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "user_id BIGINT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE, "
        "token_hash TEXT NOT NULL UNIQUE, "
        "verification_code_hash TEXT NOT NULL, "
        "verified_at TIMESTAMPTZ NULL, "
        "expires_at TIMESTAMPTZ NOT NULL, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), "
        "CONSTRAINT password_reset_tokens_token_hash_not_blank CHECK (btrim(token_hash) <> ''), "
        "CONSTRAINT password_reset_tokens_verification_code_hash_not_blank CHECK (btrim(verification_code_hash) <> '')"
        ")"
    )) {
        return FailableOperationResult::ok();
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Cannot ensure password reset schema: %1").arg(query.lastError().text())
    );
}

FailableOperationResult PgDatabase::ensurePasswordResetCleanupFunction() {
    QSqlQuery query(this->database);
    if (query.exec(
        "CREATE OR REPLACE FUNCTION public.cleanup_expired_password_reset_tokens_job() "
        "RETURNS integer "
        "LANGUAGE SQL "
        "AS $$ "
        "WITH deleted AS ("
        "    DELETE FROM public.password_reset_tokens "
        "    WHERE expires_at <= NOW() "
        "    RETURNING 1"
        ") "
        "SELECT COUNT(*)::integer FROM deleted"
        "$$"
    )) {
        return FailableOperationResult::ok();
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Cannot ensure password reset cleanup function: %1").arg(query.lastError().text())
    );
}

FailableOperationResult PgDatabase::ensurePasswordResetCleanupJob() {
    QSqlQuery extensionAvailableQuery(this->database);
    extensionAvailableQuery.prepare(
        "SELECT EXISTS("
        "SELECT 1 "
        "FROM pg_available_extensions "
        "WHERE name = 'pg_cron'"
        ")"
    );
    if (!extensionAvailableQuery.exec() || !extensionAvailableQuery.next()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot inspect pg_cron availability: %1").arg(extensionAvailableQuery.lastError().text())
        );
    }

    if (!extensionAvailableQuery.value(0).toBool()) {
        qWarning().noquote() << "[-] pg_cron is not available in this PostgreSQL cluster, background cleanup job was not created";
        return FailableOperationResult::ok();
    }

    QSqlQuery extensionInstalledQuery(this->database);
    extensionInstalledQuery.prepare(
        "SELECT EXISTS("
        "SELECT 1 "
        "FROM pg_extension "
        "WHERE extname = 'pg_cron'"
        ")"
    );
    if (!extensionInstalledQuery.exec() || !extensionInstalledQuery.next()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot inspect installed pg_cron extension: %1").arg(extensionInstalledQuery.lastError().text())
        );
    }

    if (!extensionInstalledQuery.value(0).toBool()) {
        QSqlQuery createExtensionQuery(this->database);
        if (!createExtensionQuery.exec("CREATE EXTENSION IF NOT EXISTS pg_cron")) {
            qWarning().noquote() << "[-] Cannot create pg_cron extension, background cleanup job was not created:"
                                 << createExtensionQuery.lastError().text();
            return FailableOperationResult::ok();
        }
    }

    QSqlQuery existingJobQuery(this->database);
    existingJobQuery.prepare(
        "SELECT jobid "
        "FROM cron.job "
        "WHERE jobname = :job_name "
        "LIMIT 1"
    );
    existingJobQuery.bindValue(":job_name", kPasswordResetCleanupJobName);
    if (!existingJobQuery.exec()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot inspect password reset cleanup cron job: %1").arg(existingJobQuery.lastError().text())
        );
    }

    if (existingJobQuery.next()) {
        QSqlQuery alterJobQuery(this->database);
        alterJobQuery.prepare(
            "SELECT cron.alter_job("
            ":job_id, "
            ":schedule, "
            ":command"
            ")"
        );
        alterJobQuery.bindValue(":job_id", existingJobQuery.value(0));
        alterJobQuery.bindValue(":schedule", kPasswordResetCleanupJobSchedule);
        alterJobQuery.bindValue(":command", kPasswordResetCleanupJobCommand);
        if (alterJobQuery.exec()) {
            return FailableOperationResult::ok();
        }

        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot update password reset cleanup cron job: %1").arg(alterJobQuery.lastError().text())
        );
    }

    QSqlQuery scheduleJobQuery(this->database);
    scheduleJobQuery.prepare(
        "SELECT cron.schedule("
        ":job_name, "
        ":schedule, "
        ":command"
        ")"
    );
    scheduleJobQuery.bindValue(":job_name", kPasswordResetCleanupJobName);
    scheduleJobQuery.bindValue(":schedule", kPasswordResetCleanupJobSchedule);
    scheduleJobQuery.bindValue(":command", kPasswordResetCleanupJobCommand);
    if (scheduleJobQuery.exec()) {
        return FailableOperationResult::ok();
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Cannot create password reset cleanup cron job: %1").arg(scheduleJobQuery.lastError().text())
    );
}

FailableOperationResult PgDatabase::cleanupExpiredPasswordResetTokens() {
    QSqlQuery query(this->database);
    if (query.exec("DELETE FROM public.password_reset_tokens WHERE expires_at <= NOW()")) {
        return FailableOperationResult::ok();
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Cannot cleanup expired password reset tokens: %1").arg(query.lastError().text())
    );
}

QString PgDatabase::generateResetToken() const {
    QString token;
    for (int i = 0; i < 4; ++i) {
        token.append(QString("%1").arg(
            static_cast<qulonglong>(QRandomGenerator::system()->generate64()),
            16,
            16,
            QLatin1Char('0')
        ));
    }

    return token;
}

QString PgDatabase::generateVerificationCode() const {
    return QString("%1").arg(QRandomGenerator::system()->bounded(1000000), 6, 10, QLatin1Char('0'));
}

FailableOperationResult PgDatabase::connect() {
    if (this->database.isOpen()) {
        return FailableOperationResult::ok();
    }

    QString hostName = this->getEnvValue("DB_HOST", "PGHOST");
    QString portValue = this->getEnvValue("DB_PORT", "PGPORT");
    QString databaseName = this->getEnvValue("DB_NAME", "PGDATABASE");
    QString userName = this->getEnvValue("DB_USER", "PGUSER");
    QString password = this->getEnvValue("DB_PASSWORD", "PGPASSWORD");

    if (hostName.isEmpty() || portValue.isEmpty() || databaseName.isEmpty() || userName.isEmpty() || password.isEmpty()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            "Database connection env is incomplete; expected DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD"
        );
    }

    bool portOk = false;
    int port = portValue.toInt(&portOk);
    if (!portOk) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Invalid DB_PORT value: %1").arg(portValue)
        );
    }

    this->database.setHostName(hostName);
    this->database.setPort(port);
    this->database.setDatabaseName(databaseName);
    this->database.setUserName(userName);
    this->database.setPassword(password);

    if (!this->database.open()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot connect to PostgreSQL %1:%2/%3 as %4: %5")
                .arg(hostName)
                .arg(port)
                .arg(databaseName)
                .arg(userName)
                .arg(this->database.lastError().text())
        );
    }

    FailableOperationResult pgCryptoResult = this->ensurePgCrypto();
    if (!pgCryptoResult.success) {
        return pgCryptoResult;
    }

    FailableOperationResult passwordResetSchemaResult = this->ensurePasswordResetSchema();
    if (!passwordResetSchemaResult.success) {
        return passwordResetSchemaResult;
    }

    FailableOperationResult cleanupFunctionResult = this->ensurePasswordResetCleanupFunction();
    if (!cleanupFunctionResult.success) {
        return cleanupFunctionResult;
    }

    return this->ensurePasswordResetCleanupJob();
}

PgDatabase& PgDatabase::instance() {
    static PgDatabase database;
    return database;
}

FailableOperationResult PgDatabase::sync() {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    if (!this->database.transaction()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot start sync transaction: %1").arg(this->database.lastError().text())
        );
    }

    QSqlQuery cleanupQuery(this->database);
    if (!cleanupQuery.exec(
        "SELECT format('DROP TABLE IF EXISTS public.%I CASCADE', tablename) "
        "FROM pg_tables "
        "WHERE schemaname = 'public'"
    )) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot prepare sync cleanup: %1").arg(cleanupQuery.lastError().text())
        );
    }

    QStringList statements;
    while (cleanupQuery.next()) {
        statements.append(cleanupQuery.value(0).toString());
    }

    statements.append(QStringList{
        "CREATE EXTENSION IF NOT EXISTS pgcrypto",
        "CREATE TABLE public.users ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "email TEXT NOT NULL UNIQUE, "
        "password_hash TEXT NOT NULL, "
        "name TEXT NOT NULL, "
        "login TEXT NOT NULL UNIQUE, "
        "CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''), "
        "CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> ''), "
        "CONSTRAINT users_name_not_blank CHECK (btrim(name) <> ''), "
        "CONSTRAINT users_login_not_blank CHECK (btrim(login) <> '')"
        ")",
        "CREATE TABLE public.password_reset_tokens ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "user_id BIGINT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE, "
        "token_hash TEXT NOT NULL UNIQUE, "
        "verification_code_hash TEXT NOT NULL, "
        "verified_at TIMESTAMPTZ NULL, "
        "expires_at TIMESTAMPTZ NOT NULL, "
        "created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), "
        "CONSTRAINT password_reset_tokens_token_hash_not_blank CHECK (btrim(token_hash) <> ''), "
        "CONSTRAINT password_reset_tokens_verification_code_hash_not_blank CHECK (btrim(verification_code_hash) <> '')"
        ")",
        "CREATE OR REPLACE FUNCTION public.cleanup_expired_password_reset_tokens_job() "
        "RETURNS integer "
        "LANGUAGE SQL "
        "AS $$ "
        "WITH deleted AS ("
        "    DELETE FROM public.password_reset_tokens "
        "    WHERE expires_at <= NOW() "
        "    RETURNING 1"
        ") "
        "SELECT COUNT(*)::integer FROM deleted"
        "$$"
    });

    QSqlQuery query(this->database);
    for (QStringList::const_iterator it = statements.begin(); it != statements.end(); ++it) {
        if (!query.exec(*it)) {
            this->database.rollback();
            return FailableOperationResult::error(
                (int)GraphingErrorCode::InternalError,
                QString("Sync query failed: %1").arg(query.lastError().text())
            );
        }
    }

    if (!this->database.commit()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot commit sync transaction: %1").arg(this->database.lastError().text())
        );
    }

    return this->ensurePasswordResetCleanupJob();
}

FailableOperationResult PgDatabase::login(const QString& login, const QString& password) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    QSqlQuery query(this->database);
    query.prepare(
        "SELECT 1 "
        "FROM public.users "
        "WHERE login = :login "
        "AND password_hash = crypt(:password, password_hash)"
    );
    query.bindValue(":login", login);
    query.bindValue(":password", password);

    if (!query.exec()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Login query failed: %1").arg(query.lastError().text())
        );
    }

    if (!query.next()) {
        return FailableOperationResult::error((int)GraphingErrorCode::Forbidden, "Incorrect credentials");
    }

    return FailableOperationResult::ok();
}

FailableOperationResult PgDatabase::registerUser(const QString& login, const QString& password, const QString& name, const QString& email) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    if (password.isEmpty()) {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Password cannot be blank");
    }

    QSqlQuery query(this->database);
    query.prepare(
        "INSERT INTO public.users (email, password_hash, name, login) "
        "VALUES (:email, crypt(:password, gen_salt('bf', 12)), :name, :login)"
    );
    query.bindValue(":email", email);
    query.bindValue(":password", password);
    query.bindValue(":name", name);
    query.bindValue(":login", login);

    if (query.exec()) {
        return FailableOperationResult::ok();
    }

    QString nativeCode = query.lastError().nativeErrorCode();
    if (nativeCode == "23505") {
        return FailableOperationResult::error((int)GraphingErrorCode::Conflict, "User with this login or email already exists");
    }
    if (nativeCode == "23514") {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Registration fields cannot be blank");
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Registration query failed: %1").arg(query.lastError().text())
    );
}

PasswordResetCreationResult PgDatabase::createPasswordReset(const QString& loginOrEmail) {
    PasswordResetCreationResult result;

    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        result.operation = connectionResult;
        return result;
    }

    if (loginOrEmail.isEmpty()) {
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::BadRequest,
            "Password reset requires login or email"
        );
        return result;
    }

    FailableOperationResult cleanupResult = this->cleanupExpiredPasswordResetTokens();
    if (!cleanupResult.success) {
        result.operation = cleanupResult;
        return result;
    }

    QSqlQuery userQuery(this->database);
    userQuery.prepare(
        "SELECT id, email, name "
        "FROM public.users "
        "WHERE login = :login OR email = :email "
        "LIMIT 1"
    );
    userQuery.bindValue(":login", loginOrEmail);
    userQuery.bindValue(":email", loginOrEmail);

    if (!userQuery.exec()) {
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Password reset lookup failed: %1").arg(userQuery.lastError().text())
        );
        return result;
    }

    if (!userQuery.next()) {
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::BadRequest,
            "User with this login or email was not found"
        );
        return result;
    }

    qlonglong userId = userQuery.value(0).toLongLong();
    result.email = userQuery.value(1).toString();
    result.name = userQuery.value(2).toString();
    result.token = this->generateResetToken();
    result.verificationCode = this->generateVerificationCode();

    if (!this->database.transaction()) {
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot start password reset transaction: %1").arg(this->database.lastError().text())
        );
        return result;
    }

    QSqlQuery deleteExistingQuery(this->database);
    deleteExistingQuery.prepare("DELETE FROM public.password_reset_tokens WHERE user_id = :user_id");
    deleteExistingQuery.bindValue(":user_id", userId);
    if (!deleteExistingQuery.exec()) {
        this->database.rollback();
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot replace password reset token: %1").arg(deleteExistingQuery.lastError().text())
        );
        return result;
    }

    QSqlQuery insertQuery(this->database);
    insertQuery.prepare(
        "INSERT INTO public.password_reset_tokens (user_id, token_hash, verification_code_hash, expires_at) "
        "VALUES ("
        ":user_id, "
        "crypt(:token, gen_salt('bf', 12)), "
        "crypt(:verification_code, gen_salt('bf', 12)), "
        "NOW() + INTERVAL '24 hours'"
        ")"
    );
    insertQuery.bindValue(":user_id", userId);
    insertQuery.bindValue(":token", result.token);
    insertQuery.bindValue(":verification_code", result.verificationCode);
    if (!insertQuery.exec()) {
        this->database.rollback();
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot create password reset token: %1").arg(insertQuery.lastError().text())
        );
        return result;
    }

    if (!this->database.commit()) {
        this->database.rollback();
        result.operation = FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot commit password reset transaction: %1").arg(this->database.lastError().text())
        );
        return result;
    }

    result.operation = FailableOperationResult::ok();
    return result;
}

FailableOperationResult PgDatabase::cancelPasswordReset(const QString& token) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    if (token.isEmpty()) {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Password reset token cannot be blank");
    }

    FailableOperationResult cleanupResult = this->cleanupExpiredPasswordResetTokens();
    if (!cleanupResult.success) {
        return cleanupResult;
    }

    QSqlQuery query(this->database);
    query.prepare("DELETE FROM public.password_reset_tokens WHERE token_hash = crypt(:token, token_hash)");
    query.bindValue(":token", token);
    if (!query.exec()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot cancel password reset token: %1").arg(query.lastError().text())
        );
    }

    return FailableOperationResult::ok();
}

FailableOperationResult PgDatabase::verifyPasswordReset(const QString& token, const QString& verificationCode) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    if (token.isEmpty()) {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Password reset token cannot be blank");
    }

    if (verificationCode.isEmpty()) {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Verification code cannot be blank");
    }

    FailableOperationResult cleanupResult = this->cleanupExpiredPasswordResetTokens();
    if (!cleanupResult.success) {
        return cleanupResult;
    }

    QSqlQuery stateQuery(this->database);
    stateQuery.prepare(
        "SELECT verified_at IS NOT NULL, verification_code_hash = crypt(:verification_code, verification_code_hash) "
        "FROM public.password_reset_tokens "
        "WHERE token_hash = crypt(:token, token_hash) "
        "AND expires_at > NOW()"
    );
    stateQuery.bindValue(":token", token);
    stateQuery.bindValue(":verification_code", verificationCode);
    if (!stateQuery.exec()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot verify password reset token: %1").arg(stateQuery.lastError().text())
        );
    }

    if (!stateQuery.next()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::BadRequest,
            "Password reset token is invalid or expired"
        );
    }

    bool alreadyVerified = stateQuery.value(0).toBool();
    bool codeMatches = stateQuery.value(1).toBool();
    if (alreadyVerified) {
        return FailableOperationResult::ok();
    }

    if (!codeMatches) {
        return FailableOperationResult::error((int)GraphingErrorCode::Forbidden, "Incorrect verification code");
    }

    QSqlQuery updateQuery(this->database);
    updateQuery.prepare(
        "UPDATE public.password_reset_tokens "
        "SET verified_at = NOW() "
        "WHERE token_hash = crypt(:token, token_hash) "
        "AND expires_at > NOW() "
        "AND verified_at IS NULL"
    );
    updateQuery.bindValue(":token", token);
    if (!updateQuery.exec()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot mark password reset token as verified: %1").arg(updateQuery.lastError().text())
        );
    }

    return FailableOperationResult::ok();
}

FailableOperationResult PgDatabase::resetPassword(const QString& token, const QString& newPassword) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    if (token.isEmpty()) {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Password reset token cannot be blank");
    }

    if (newPassword.isEmpty()) {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Password cannot be blank");
    }

    FailableOperationResult cleanupResult = this->cleanupExpiredPasswordResetTokens();
    if (!cleanupResult.success) {
        return cleanupResult;
    }

    if (!this->database.transaction()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot start password update transaction: %1").arg(this->database.lastError().text())
        );
    }

    QSqlQuery tokenQuery(this->database);
    tokenQuery.prepare(
        "SELECT user_id, verified_at IS NOT NULL "
        "FROM public.password_reset_tokens "
        "WHERE token_hash = crypt(:token, token_hash) "
        "AND expires_at > NOW() "
        "FOR UPDATE"
    );
    tokenQuery.bindValue(":token", token);
    if (!tokenQuery.exec()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot load password reset token: %1").arg(tokenQuery.lastError().text())
        );
    }

    if (!tokenQuery.next()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::BadRequest,
            "Password reset token is invalid or expired"
        );
    }

    qlonglong userId = tokenQuery.value(0).toLongLong();
    bool isVerified = tokenQuery.value(1).toBool();
    if (!isVerified) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::Forbidden,
            "Password reset code is not verified"
        );
    }

    QSqlQuery updatePasswordQuery(this->database);
    updatePasswordQuery.prepare(
        "UPDATE public.users "
        "SET password_hash = crypt(:password, gen_salt('bf', 12)) "
        "WHERE id = :user_id"
    );
    updatePasswordQuery.bindValue(":password", newPassword);
    updatePasswordQuery.bindValue(":user_id", userId);
    if (!updatePasswordQuery.exec()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot update password: %1").arg(updatePasswordQuery.lastError().text())
        );
    }

    QSqlQuery deleteTokensQuery(this->database);
    deleteTokensQuery.prepare("DELETE FROM public.password_reset_tokens WHERE user_id = :user_id");
    deleteTokensQuery.bindValue(":user_id", userId);
    if (!deleteTokensQuery.exec()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot cleanup password reset tokens: %1").arg(deleteTokensQuery.lastError().text())
        );
    }

    if (!this->database.commit()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot commit password update transaction: %1").arg(this->database.lastError().text())
        );
    }

    return FailableOperationResult::ok();
}
