#include "PgDatabase.h"
#include "GraphingErrorCode.h"
#include <QProcessEnvironment>
#include <QSqlError>
#include <QSqlQuery>
#include <QVariant>

namespace {
    const char* kConnectionName = "graphing_server_pg_database";
}

PgDatabase::PgDatabase() {
    if (QSqlDatabase::contains(kConnectionName)) {
        this->database = QSqlDatabase::database(kConnectionName);
    } else {
        this->database = QSqlDatabase::addDatabase("QPSQL", kConnectionName);
    }
}

QString PgDatabase::getEnvValue(const char* primaryName, const char* fallbackName) const {
    QString value = qEnvironmentVariable(primaryName);
    if (!value.isEmpty()) {
        return value;
    }

    if (fallbackName) {
        value = qEnvironmentVariable(fallbackName);
        if (!value.isEmpty()) {
            return value;
        }
    }

    return "";
}

FailableOperationResult PgDatabase::ensurePgCrypto() {
    QSqlQuery query(this->database);
    if (query.exec("CREATE EXTENSION IF NOT EXISTS pgcrypto")) {
        return FailableOperationResult::ok();
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Cannot enable pgcrypto: %1").arg(query.lastError().text())
    );
}

FailableOperationResult PgDatabase::connect() {
    if (this->database.isOpen()) {
        return FailableOperationResult::ok();
    }

    QString hostName = this->getEnvValue("DB_HOST", "PGHOST");
    QString portValue = this->getEnvValue("DB_PORT", "PGPORT");
    QString databaseName = this->getEnvValue("DB_NAME", "PGDATABASE");
    QString userName = this->getEnvValue("DB_USER", "PGUSER");
    QString password = this->getEnvValue("DB_PASSWORD", "PGPASSWORD");

    if (hostName.isEmpty() || portValue.isEmpty() || databaseName.isEmpty() || userName.isEmpty() || password.isEmpty()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            "Database connection env is incomplete; expected DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD"
        );
    }

    bool portOk = false;
    int port = portValue.toInt(&portOk);
    if (!portOk) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Invalid DB_PORT value: %1").arg(portValue)
        );
    }

    this->database.setHostName(hostName);
    this->database.setPort(port);
    this->database.setDatabaseName(databaseName);
    this->database.setUserName(userName);
    this->database.setPassword(password);

    if (!this->database.open()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot connect to PostgreSQL %1:%2/%3 as %4: %5")
                .arg(hostName)
                .arg(port)
                .arg(databaseName)
                .arg(userName)
                .arg(this->database.lastError().text())
        );
    }

    return this->ensurePgCrypto();
}

PgDatabase& PgDatabase::instance() {
    static PgDatabase database;
    return database;
}

FailableOperationResult PgDatabase::sync() {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    if (!this->database.transaction()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot start sync transaction: %1").arg(this->database.lastError().text())
        );
    }

    QSqlQuery cleanupQuery(this->database);
    if (!cleanupQuery.exec(
        "SELECT format('DROP TABLE IF EXISTS public.%I CASCADE', tablename) "
        "FROM pg_tables "
        "WHERE schemaname = 'public'"
    )) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot prepare sync cleanup: %1").arg(cleanupQuery.lastError().text())
        );
    }

    QStringList statements;
    while (cleanupQuery.next()) {
        statements.append(cleanupQuery.value(0).toString());
    }

    statements.append(QStringList{
        "CREATE EXTENSION IF NOT EXISTS pgcrypto",
        "CREATE TABLE public.users ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
        "email TEXT NOT NULL UNIQUE, "
        "password_hash TEXT NOT NULL, "
        "name TEXT NOT NULL, "
        "login TEXT NOT NULL UNIQUE, "
        "CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''), "
        "CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> ''), "
        "CONSTRAINT users_name_not_blank CHECK (btrim(name) <> ''), "
        "CONSTRAINT users_login_not_blank CHECK (btrim(login) <> '')"
        ")"
    });

    QSqlQuery query(this->database);
    for (QStringList::const_iterator it = statements.begin(); it != statements.end(); ++it) {
        if (!query.exec(*it)) {
            this->database.rollback();
            return FailableOperationResult::error(
                (int)GraphingErrorCode::InternalError,
                QString("Sync query failed: %1").arg(query.lastError().text())
            );
        }
    }

    if (!this->database.commit()) {
        this->database.rollback();
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Cannot commit sync transaction: %1").arg(this->database.lastError().text())
        );
    }

    return FailableOperationResult::ok();
}

FailableOperationResult PgDatabase::login(const QString& login, const QString& password) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    QSqlQuery query(this->database);
    query.prepare(
        "SELECT 1 "
        "FROM public.users "
        "WHERE login = :login "
        "AND password_hash = crypt(:password, password_hash)"
    );
    query.bindValue(":login", login);
    query.bindValue(":password", password);

    if (!query.exec()) {
        return FailableOperationResult::error(
            (int)GraphingErrorCode::InternalError,
            QString("Login query failed: %1").arg(query.lastError().text())
        );
    }

    if (!query.next()) {
        return FailableOperationResult::error((int)GraphingErrorCode::Forbidden, "Incorrect credentials");
    }

    return FailableOperationResult::ok();
}

FailableOperationResult PgDatabase::registerUser(const QString& login, const QString& password, const QString& name, const QString& email) {
    FailableOperationResult connectionResult = this->connect();
    if (!connectionResult.success) {
        return connectionResult;
    }

    QSqlQuery query(this->database);
    query.prepare(
        "INSERT INTO public.users (email, password_hash, name, login) "
        "VALUES (:email, crypt(:password, gen_salt('bf', 12)), :name, :login)"
    );
    query.bindValue(":email", email);
    query.bindValue(":password", password);
    query.bindValue(":name", name);
    query.bindValue(":login", login);

    if (query.exec()) {
        return FailableOperationResult::ok();
    }

    QString nativeCode = query.lastError().nativeErrorCode();
    if (nativeCode == "23505") {
        return FailableOperationResult::error((int)GraphingErrorCode::Conflict, "User with this login or email already exists");
    }
    if (nativeCode == "23514") {
        return FailableOperationResult::error((int)GraphingErrorCode::BadRequest, "Registration fields cannot be blank");
    }

    return FailableOperationResult::error(
        (int)GraphingErrorCode::InternalError,
        QString("Registration query failed: %1").arg(query.lastError().text())
    );
}
