#!/usr/bin/env bash
set -euo pipefail

: "${APP_DB_NAME:=calc_db}"
: "${APP_DB_USER:=calc_app}"
: "${APP_DB_PASSWORD:=calc_app_password}"

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname postgres \
    -v app_db_name="$APP_DB_NAME" \
    -v app_db_user="$APP_DB_USER" \
    -v app_db_password="$APP_DB_PASSWORD" <<'SQL'
SELECT CASE
  WHEN EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_db_user')
    THEN format('ALTER ROLE %I WITH LOGIN PASSWORD %L', :'app_db_user', :'app_db_password')
  ELSE
    format('CREATE ROLE %I LOGIN PASSWORD %L', :'app_db_user', :'app_db_password')
END \gexec

SELECT format('CREATE DATABASE %I OWNER %I', :'app_db_name', :'app_db_user')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'app_db_name') \gexec

SELECT format('ALTER DATABASE %I OWNER TO %I', :'app_db_name', :'app_db_user') \gexec
SQL

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname "$APP_DB_NAME" \
    -v app_db_user="$APP_DB_USER" <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    login TEXT NOT NULL UNIQUE,
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT users_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT users_login_not_blank CHECK (btrim(login) <> '')
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    verification_code_hash TEXT NOT NULL,
    verified_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cancelled_at TIMESTAMPTZ NULL,
    replaced_at TIMESTAMPTZ NULL,
    used_at TIMESTAMPTZ NULL,
    email_failed_at TIMESTAMPTZ NULL,
    failure_message TEXT NULL,
    CONSTRAINT password_reset_tokens_token_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT password_reset_tokens_verification_code_hash_not_blank CHECK (btrim(verification_code_hash) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS password_reset_tokens_one_active_per_user
ON public.password_reset_tokens (user_id)
WHERE cancelled_at IS NULL
    AND replaced_at IS NULL
    AND used_at IS NULL
    AND email_failed_at IS NULL;

CREATE INDEX IF NOT EXISTS password_reset_tokens_user_id_created_at_idx
ON public.password_reset_tokens (user_id, created_at DESC);

ALTER TABLE public.users OWNER TO :app_db_user;
ALTER TABLE public.password_reset_tokens OWNER TO :app_db_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :app_db_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :app_db_user;
SQL
