#!/usr/bin/env bash
set -euo pipefail

: "${APP_DB_NAME:=calc_db}"
: "${APP_DB_USER:=calc_app}"
: "${APP_DB_PASSWORD:=calc_app_password}"

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname postgres \
    -v app_db_name="$APP_DB_NAME" \
    -v app_db_user="$APP_DB_USER" \
    -v app_db_password="$APP_DB_PASSWORD" <<'SQL'
SELECT CASE
  WHEN EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'app_db_user')
    THEN format('ALTER ROLE %I WITH LOGIN PASSWORD %L', :'app_db_user', :'app_db_password')
  ELSE
    format('CREATE ROLE %I LOGIN PASSWORD %L', :'app_db_user', :'app_db_password')
END \gexec

SELECT format('CREATE DATABASE %I OWNER %I', :'app_db_name', :'app_db_user')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = :'app_db_name') \gexec

SELECT format('ALTER DATABASE %I OWNER TO %I', :'app_db_name', :'app_db_user') \gexec
SQL

psql -v ON_ERROR_STOP=1 \
    --username "$POSTGRES_USER" \
    --dbname "$APP_DB_NAME" \
    -v app_db_user="$APP_DB_USER" <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pg_cron;

GRANT USAGE ON SCHEMA cron TO :app_db_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA cron TO :app_db_user;
GRANT SELECT ON TABLE cron.job TO :app_db_user;

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    login TEXT NOT NULL UNIQUE,
    CONSTRAINT users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT users_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT users_login_not_blank CHECK (btrim(login) <> '')
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    verification_code_hash TEXT NOT NULL,
    verified_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT password_reset_tokens_token_hash_not_blank CHECK (btrim(token_hash) <> ''),
    CONSTRAINT password_reset_tokens_verification_code_hash_not_blank CHECK (btrim(verification_code_hash) <> '')
);

CREATE OR REPLACE FUNCTION public.cleanup_expired_password_reset_tokens_job()
RETURNS integer
LANGUAGE SQL
AS $$
WITH deleted AS (
    DELETE FROM public.password_reset_tokens
    WHERE expires_at <= NOW()
    RETURNING 1
)
SELECT COUNT(*)::integer FROM deleted
$$;

ALTER TABLE public.users OWNER TO :app_db_user;
ALTER TABLE public.password_reset_tokens OWNER TO :app_db_user;
ALTER FUNCTION public.cleanup_expired_password_reset_tokens_job() OWNER TO :app_db_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :app_db_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :app_db_user;
SQL
