// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DB_MODELS_ODB_HXX
#define DB_MODELS_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <odb/boost/date-time/pgsql/gregorian-traits.hxx>
#include <odb/boost/date-time/pgsql/posix-time-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "DbModels.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // DbUser
  //
  template <>
  struct class_traits< ::DbUser >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DbUser >
  {
    public:
    typedef ::DbUser object_type;
    typedef ::DbUser* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DbPasswordResetToken
  //
  template <>
  struct class_traits< ::DbPasswordResetToken >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::DbPasswordResetToken >
  {
    public:
    typedef ::DbPasswordResetToken object_type;
    typedef ::DbPasswordResetToken* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // DbSchemaState
  //
  template <>
  struct class_traits< ::DbSchemaState >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::DbSchemaState >
  {
    public:
    typedef ::DbSchemaState view_type;
    typedef ::DbSchemaState* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // DbStringValue
  //
  template <>
  struct class_traits< ::DbStringValue >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::DbStringValue >
  {
    public:
    typedef ::DbStringValue view_type;
    typedef ::DbStringValue* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // DbBoolValue
  //
  template <>
  struct class_traits< ::DbBoolValue >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::DbBoolValue >
  {
    public:
    typedef ::DbBoolValue view_type;
    typedef ::DbBoolValue* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // DbIdValue
  //
  template <>
  struct class_traits< ::DbIdValue >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::DbIdValue >
  {
    public:
    typedef ::DbIdValue view_type;
    typedef ::DbIdValue* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // DbPasswordResetVerificationState
  //
  template <>
  struct class_traits< ::DbPasswordResetVerificationState >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::DbPasswordResetVerificationState >
  {
    public:
    typedef ::DbPasswordResetVerificationState view_type;
    typedef ::DbPasswordResetVerificationState* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };

  // DbPasswordResetUpdateState
  //
  template <>
  struct class_traits< ::DbPasswordResetUpdateState >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::DbPasswordResetUpdateState >
  {
    public:
    typedef ::DbPasswordResetUpdateState view_type;
    typedef ::DbPasswordResetUpdateState* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // DbUser
  //
  template <typename A>
  struct query_columns< ::DbUser, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // email
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    email_type_;

    static const email_type_ email;

    // passwordHash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    passwordHash_type_;

    static const passwordHash_type_ passwordHash;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;

    // login
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    login_type_;

    static const login_type_ login;
  };

  template <typename A>
  const typename query_columns< ::DbUser, id_pgsql, A >::id_type_
  query_columns< ::DbUser, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::DbUser, id_pgsql, A >::email_type_
  query_columns< ::DbUser, id_pgsql, A >::
  email (A::table_name, "\"email\"", 0);

  template <typename A>
  const typename query_columns< ::DbUser, id_pgsql, A >::passwordHash_type_
  query_columns< ::DbUser, id_pgsql, A >::
  passwordHash (A::table_name, "\"password_hash\"", 0);

  template <typename A>
  const typename query_columns< ::DbUser, id_pgsql, A >::name_type_
  query_columns< ::DbUser, id_pgsql, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::DbUser, id_pgsql, A >::login_type_
  query_columns< ::DbUser, id_pgsql, A >::
  login (A::table_name, "\"login\"", 0);

  template <typename A>
  struct pointer_query_columns< ::DbUser, id_pgsql, A >:
    query_columns< ::DbUser, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::DbUser, id_pgsql >:
    public access::object_traits< ::DbUser >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // email_
      //
      details::buffer email_value;
      std::size_t email_size;
      bool email_null;

      // passwordHash_
      //
      details::buffer passwordHash_value;
      std::size_t passwordHash_size;
      bool passwordHash_null;

      // name_
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // login_
      //
      details::buffer login_value;
      std::size_t login_size;
      bool login_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DbUser, id_common >:
    public access::object_traits_impl< ::DbUser, id_pgsql >
  {
  };

  // DbPasswordResetToken
  //
  template <typename A>
  struct query_columns< ::DbPasswordResetToken, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // userId
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    userId_type_;

    static const userId_type_ userId;

    // tokenHash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    tokenHash_type_;

    static const tokenHash_type_ tokenHash;

    // verificationCodeHash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    verificationCodeHash_type_;

    static const verificationCodeHash_type_ verificationCodeHash;

    // verifiedAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    verifiedAt_type_;

    static const verifiedAt_type_ verifiedAt;

    // expiresAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::DbPasswordResetToken::Timestamp,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    expiresAt_type_;

    static const expiresAt_type_ expiresAt;

    // createdAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::DbPasswordResetToken::Timestamp,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    createdAt_type_;

    static const createdAt_type_ createdAt;

    // cancelledAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    cancelledAt_type_;

    static const cancelledAt_type_ cancelledAt;

    // replacedAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    replacedAt_type_;

    static const replacedAt_type_ replacedAt;

    // usedAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    usedAt_type_;

    static const usedAt_type_ usedAt;

    // emailFailedAt
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    emailFailedAt_type_;

    static const emailFailedAt_type_ emailFailedAt;

    // failureMessage
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    failureMessage_type_;

    static const failureMessage_type_ failureMessage;
  };

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::id_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::userId_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  userId (A::table_name, "\"user_id\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::tokenHash_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  tokenHash (A::table_name, "\"token_hash\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::verificationCodeHash_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  verificationCodeHash (A::table_name, "\"verification_code_hash\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::verifiedAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  verifiedAt (A::table_name, "\"verified_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::expiresAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  expiresAt (A::table_name, "\"expires_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::createdAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  createdAt (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::cancelledAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  cancelledAt (A::table_name, "\"cancelled_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::replacedAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  replacedAt (A::table_name, "\"replaced_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::usedAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  usedAt (A::table_name, "\"used_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::emailFailedAt_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  emailFailedAt (A::table_name, "\"email_failed_at\"", 0);

  template <typename A>
  const typename query_columns< ::DbPasswordResetToken, id_pgsql, A >::failureMessage_type_
  query_columns< ::DbPasswordResetToken, id_pgsql, A >::
  failureMessage (A::table_name, "\"failure_message\"", 0);

  template <typename A>
  struct pointer_query_columns< ::DbPasswordResetToken, id_pgsql, A >:
    query_columns< ::DbPasswordResetToken, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >:
    public access::object_traits< ::DbPasswordResetToken >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // userId_
      //
      long long userId_value;
      bool userId_null;

      // tokenHash_
      //
      details::buffer tokenHash_value;
      std::size_t tokenHash_size;
      bool tokenHash_null;

      // verificationCodeHash_
      //
      details::buffer verificationCodeHash_value;
      std::size_t verificationCodeHash_size;
      bool verificationCodeHash_null;

      // verifiedAt_
      //
      long long verifiedAt_value;
      bool verifiedAt_null;

      // expiresAt_
      //
      long long expiresAt_value;
      bool expiresAt_null;

      // createdAt_
      //
      long long createdAt_value;
      bool createdAt_null;

      // cancelledAt_
      //
      long long cancelledAt_value;
      bool cancelledAt_null;

      // replacedAt_
      //
      long long replacedAt_value;
      bool replacedAt_null;

      // usedAt_
      //
      long long usedAt_value;
      bool usedAt_null;

      // emailFailedAt_
      //
      long long emailFailedAt_value;
      bool emailFailedAt_null;

      // failureMessage_
      //
      details::buffer failureMessage_value;
      std::size_t failureMessage_size;
      bool failureMessage_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 12UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::DbPasswordResetToken, id_common >:
    public access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >
  {
  };

  // DbSchemaState
  //
  template <>
  class access::view_traits_impl< ::DbSchemaState, id_pgsql >:
    public access::view_traits< ::DbSchemaState >
  {
    public:
    struct image_type
    {
      // usersExists
      //
      bool usersExists_value;
      bool usersExists_null;

      // passwordResetTokensExists
      //
      bool passwordResetTokensExists_value;
      bool passwordResetTokensExists_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 2UL;

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::DbSchemaState, id_common >:
    public access::view_traits_impl< ::DbSchemaState, id_pgsql >
  {
  };

  // DbStringValue
  //
  template <>
  class access::view_traits_impl< ::DbStringValue, id_pgsql >:
    public access::view_traits< ::DbStringValue >
  {
    public:
    struct image_type
    {
      // value
      //
      details::buffer value_value;
      std::size_t value_size;
      bool value_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::DbStringValue, id_common >:
    public access::view_traits_impl< ::DbStringValue, id_pgsql >
  {
  };

  // DbBoolValue
  //
  template <>
  class access::view_traits_impl< ::DbBoolValue, id_pgsql >:
    public access::view_traits< ::DbBoolValue >
  {
    public:
    struct image_type
    {
      // value
      //
      bool value_value;
      bool value_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::DbBoolValue, id_common >:
    public access::view_traits_impl< ::DbBoolValue, id_pgsql >
  {
  };

  // DbIdValue
  //
  template <>
  class access::view_traits_impl< ::DbIdValue, id_pgsql >:
    public access::view_traits< ::DbIdValue >
  {
    public:
    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 1UL;

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::DbIdValue, id_common >:
    public access::view_traits_impl< ::DbIdValue, id_pgsql >
  {
  };

  // DbPasswordResetVerificationState
  //
  template <>
  class access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >:
    public access::view_traits< ::DbPasswordResetVerificationState >
  {
    public:
    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // alreadyVerified
      //
      bool alreadyVerified_value;
      bool alreadyVerified_null;

      // notExpired
      //
      bool notExpired_value;
      bool notExpired_null;

      // codeMatches
      //
      bool codeMatches_value;
      bool codeMatches_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 4UL;

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::DbPasswordResetVerificationState, id_common >:
    public access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >
  {
  };

  // DbPasswordResetUpdateState
  //
  template <>
  class access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >:
    public access::view_traits< ::DbPasswordResetUpdateState >
  {
    public:
    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // userId
      //
      long long userId_value;
      bool userId_null;

      // verified
      //
      bool verified_value;
      bool verified_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns
    {
    };

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 3UL;

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::DbPasswordResetUpdateState, id_common >:
    public access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >
  {
  };

  // DbUser
  //
  // DbPasswordResetToken
  //
}

#include "DbModels-odb.ixx"

#include <odb/post.hxx>

#endif // DB_MODELS_ODB_HXX
