// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "DbModels-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/view-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>
#include <odb/pgsql/view-result.hxx>

namespace odb
{
  // DbUser
  //

  const char access::object_traits_impl< ::DbUser, id_pgsql >::
  persist_statement_name[] = "persist_DbUser";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::
  find_statement_name[] = "find_DbUser";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::
  update_statement_name[] = "update_DbUser";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::
  erase_statement_name[] = "erase_DbUser";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::
  query_statement_name[] = "query_DbUser";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::
  erase_query_statement_name[] = "erase_query_DbUser";

  const unsigned int access::object_traits_impl< ::DbUser, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::DbUser, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::DbUser, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::DbUser, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::DbUser, id_pgsql >::id_type
  access::object_traits_impl< ::DbUser, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::DbUser, id_pgsql >::id_type
  access::object_traits_impl< ::DbUser, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::DbUser, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // email_
    //
    if (t[1UL])
    {
      i.email_value.capacity (i.email_size);
      grew = true;
    }

    // passwordHash_
    //
    if (t[2UL])
    {
      i.passwordHash_value.capacity (i.passwordHash_size);
      grew = true;
    }

    // name_
    //
    if (t[3UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // login_
    //
    if (t[4UL])
    {
      i.login_value.capacity (i.login_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // email_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.email_value.data ();
    b[n].capacity = i.email_value.capacity ();
    b[n].size = &i.email_size;
    b[n].is_null = &i.email_null;
    n++;

    // passwordHash_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.passwordHash_value.data ();
    b[n].capacity = i.passwordHash_value.capacity ();
    b[n].size = &i.passwordHash_size;
    b[n].is_null = &i.passwordHash_null;
    n++;

    // name_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.name_value.data ();
    b[n].capacity = i.name_value.capacity ();
    b[n].size = &i.name_size;
    b[n].is_null = &i.name_null;
    n++;

    // login_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.login_value.data ();
    b[n].capacity = i.login_value.capacity ();
    b[n].size = &i.login_size;
    b[n].is_null = &i.login_null;
    n++;
  }

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::DbUser, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // email_
    //
    {
      ::std::string const& v =
        o.email_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.email_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.email_value,
        size,
        is_null,
        v);
      i.email_null = is_null;
      i.email_size = size;
      grew = grew || (cap != i.email_value.capacity ());
    }

    // passwordHash_
    //
    {
      ::std::string const& v =
        o.passwordHash_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.passwordHash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.passwordHash_value,
        size,
        is_null,
        v);
      i.passwordHash_null = is_null;
      i.passwordHash_size = size;
      grew = grew || (cap != i.passwordHash_value.capacity ());
    }

    // name_
    //
    {
      ::std::string const& v =
        o.name_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.name_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.name_value,
        size,
        is_null,
        v);
      i.name_null = is_null;
      i.name_size = size;
      grew = grew || (cap != i.name_value.capacity ());
    }

    // login_
    //
    {
      ::std::string const& v =
        o.login_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.login_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.login_value,
        size,
        is_null,
        v);
      i.login_null = is_null;
      i.login_size = size;
      grew = grew || (cap != i.login_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long long unsigned int& v =
        o.id_;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // email_
    //
    {
      ::std::string& v =
        o.email_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.email_value,
        i.email_size,
        i.email_null);
    }

    // passwordHash_
    //
    {
      ::std::string& v =
        o.passwordHash_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.passwordHash_value,
        i.passwordHash_size,
        i.passwordHash_null);
    }

    // name_
    //
    {
      ::std::string& v =
        o.name_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.name_value,
        i.name_size,
        i.name_null);
    }

    // login_
    //
    {
      ::std::string& v =
        o.login_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.login_value,
        i.login_size,
        i.login_null);
    }
  }

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::DbUser, id_pgsql >::persist_statement[] =
  "INSERT INTO \"users\" "
  "(\"id\", "
  "\"email\", "
  "\"password_hash\", "
  "\"name\", "
  "\"login\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::find_statement[] =
  "SELECT "
  "\"users\".\"id\", "
  "\"users\".\"email\", "
  "\"users\".\"password_hash\", "
  "\"users\".\"name\", "
  "\"users\".\"login\" "
  "FROM \"users\" "
  "WHERE \"users\".\"id\"=$1";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::update_statement[] =
  "UPDATE \"users\" "
  "SET "
  "\"email\"=$1, "
  "\"password_hash\"=$2, "
  "\"name\"=$3, "
  "\"login\"=$4 "
  "WHERE \"id\"=$5";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::erase_statement[] =
  "DELETE FROM \"users\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::query_statement[] =
  "SELECT "
  "\"users\".\"id\", "
  "\"users\".\"email\", "
  "\"users\".\"password_hash\", "
  "\"users\".\"name\", "
  "\"users\".\"login\" "
  "FROM \"users\"";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"users\"";

  const char access::object_traits_impl< ::DbUser, id_pgsql >::table_name[] =
  "\"users\"";

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::DbUser, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::DbUser, id_pgsql >::pointer_type
  access::object_traits_impl< ::DbUser, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::DbUser, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::DbUser, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::DbUser, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::DbUser, id_pgsql >::object_type >
  access::object_traits_impl< ::DbUser, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::DbUser, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }

  // DbPasswordResetToken
  //

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  persist_statement_name[] = "persist_DbPasswordResetToken";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  find_statement_name[] = "find_DbPasswordResetToken";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  update_statement_name[] = "update_DbPasswordResetToken";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  erase_statement_name[] = "erase_DbPasswordResetToken";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  query_statement_name[] = "query_DbPasswordResetToken";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  erase_query_statement_name[] = "erase_query_DbPasswordResetToken";

  const unsigned int access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::int8_oid
  };

  const unsigned int access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int8_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid,
    pgsql::int8_oid
  };

  struct access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::id_type
  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  id (const id_image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::id_type
  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    t[0UL] = 0;

    // userId_
    //
    t[1UL] = 0;

    // tokenHash_
    //
    if (t[2UL])
    {
      i.tokenHash_value.capacity (i.tokenHash_size);
      grew = true;
    }

    // verificationCodeHash_
    //
    if (t[3UL])
    {
      i.verificationCodeHash_value.capacity (i.verificationCodeHash_size);
      grew = true;
    }

    // verifiedAt_
    //
    t[4UL] = 0;

    // expiresAt_
    //
    t[5UL] = 0;

    // createdAt_
    //
    t[6UL] = 0;

    // cancelledAt_
    //
    t[7UL] = 0;

    // replacedAt_
    //
    t[8UL] = 0;

    // usedAt_
    //
    t[9UL] = 0;

    // emailFailedAt_
    //
    t[10UL] = 0;

    // failureMessage_
    //
    if (t[11UL])
    {
      i.failureMessage_value.capacity (i.failureMessage_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_insert && sk != statement_update)
    {
      b[n].type = pgsql::bind::bigint;
      b[n].buffer = &i.id_value;
      b[n].is_null = &i.id_null;
      n++;
    }

    // userId_
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.userId_value;
    b[n].is_null = &i.userId_null;
    n++;

    // tokenHash_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.tokenHash_value.data ();
    b[n].capacity = i.tokenHash_value.capacity ();
    b[n].size = &i.tokenHash_size;
    b[n].is_null = &i.tokenHash_null;
    n++;

    // verificationCodeHash_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.verificationCodeHash_value.data ();
    b[n].capacity = i.verificationCodeHash_value.capacity ();
    b[n].size = &i.verificationCodeHash_size;
    b[n].is_null = &i.verificationCodeHash_null;
    n++;

    // verifiedAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.verifiedAt_value;
    b[n].is_null = &i.verifiedAt_null;
    n++;

    // expiresAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.expiresAt_value;
    b[n].is_null = &i.expiresAt_null;
    n++;

    // createdAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.createdAt_value;
    b[n].is_null = &i.createdAt_null;
    n++;

    // cancelledAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.cancelledAt_value;
    b[n].is_null = &i.cancelledAt_null;
    n++;

    // replacedAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.replacedAt_value;
    b[n].is_null = &i.replacedAt_null;
    n++;

    // usedAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.usedAt_value;
    b[n].is_null = &i.usedAt_null;
    n++;

    // emailFailedAt_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.emailFailedAt_value;
    b[n].is_null = &i.emailFailedAt_null;
    n++;

    // failureMessage_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.failureMessage_value.data ();
    b[n].capacity = i.failureMessage_value.capacity ();
    b[n].size = &i.failureMessage_size;
    b[n].is_null = &i.failureMessage_null;
    n++;
  }

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // userId_
    //
    {
      long long unsigned int const& v =
        o.userId_;

      bool is_null (false);
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_image (
        i.userId_value, is_null, v);
      i.userId_null = is_null;
    }

    // tokenHash_
    //
    {
      ::std::string const& v =
        o.tokenHash_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.tokenHash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.tokenHash_value,
        size,
        is_null,
        v);
      i.tokenHash_null = is_null;
      i.tokenHash_size = size;
      grew = grew || (cap != i.tokenHash_value.capacity ());
    }

    // verificationCodeHash_
    //
    {
      ::std::string const& v =
        o.verificationCodeHash_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.verificationCodeHash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.verificationCodeHash_value,
        size,
        is_null,
        v);
      i.verificationCodeHash_null = is_null;
      i.verificationCodeHash_size = size;
      grew = grew || (cap != i.verificationCodeHash_value.capacity ());
    }

    // verifiedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime > const& v =
        o.verifiedAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_image (
        i.verifiedAt_value, is_null, v);
      i.verifiedAt_null = is_null;
    }

    // expiresAt_
    //
    {
      ::DbPasswordResetToken::Timestamp const& v =
        o.expiresAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::DbPasswordResetToken::Timestamp,
          pgsql::id_timestamp >::set_image (
        i.expiresAt_value, is_null, v);
      i.expiresAt_null = is_null;
    }

    // createdAt_
    //
    {
      ::DbPasswordResetToken::Timestamp const& v =
        o.createdAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::DbPasswordResetToken::Timestamp,
          pgsql::id_timestamp >::set_image (
        i.createdAt_value, is_null, v);
      i.createdAt_null = is_null;
    }

    // cancelledAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime > const& v =
        o.cancelledAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_image (
        i.cancelledAt_value, is_null, v);
      i.cancelledAt_null = is_null;
    }

    // replacedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime > const& v =
        o.replacedAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_image (
        i.replacedAt_value, is_null, v);
      i.replacedAt_null = is_null;
    }

    // usedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime > const& v =
        o.usedAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_image (
        i.usedAt_value, is_null, v);
      i.usedAt_null = is_null;
    }

    // emailFailedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime > const& v =
        o.emailFailedAt_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_image (
        i.emailFailedAt_value, is_null, v);
      i.emailFailedAt_null = is_null;
    }

    // failureMessage_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.failureMessage_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.failureMessage_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_image (
        i.failureMessage_value,
        size,
        is_null,
        v);
      i.failureMessage_null = is_null;
      i.failureMessage_size = size;
      grew = grew || (cap != i.failureMessage_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      long long unsigned int& v =
        o.id_;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // userId_
    //
    {
      long long unsigned int& v =
        o.userId_;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.userId_value,
        i.userId_null);
    }

    // tokenHash_
    //
    {
      ::std::string& v =
        o.tokenHash_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.tokenHash_value,
        i.tokenHash_size,
        i.tokenHash_null);
    }

    // verificationCodeHash_
    //
    {
      ::std::string& v =
        o.verificationCodeHash_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.verificationCodeHash_value,
        i.verificationCodeHash_size,
        i.verificationCodeHash_null);
    }

    // verifiedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime >& v =
        o.verifiedAt_;

      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_value (
        v,
        i.verifiedAt_value,
        i.verifiedAt_null);
    }

    // expiresAt_
    //
    {
      ::DbPasswordResetToken::Timestamp& v =
        o.expiresAt_;

      pgsql::value_traits<
          ::DbPasswordResetToken::Timestamp,
          pgsql::id_timestamp >::set_value (
        v,
        i.expiresAt_value,
        i.expiresAt_null);
    }

    // createdAt_
    //
    {
      ::DbPasswordResetToken::Timestamp& v =
        o.createdAt_;

      pgsql::value_traits<
          ::DbPasswordResetToken::Timestamp,
          pgsql::id_timestamp >::set_value (
        v,
        i.createdAt_value,
        i.createdAt_null);
    }

    // cancelledAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime >& v =
        o.cancelledAt_;

      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_value (
        v,
        i.cancelledAt_value,
        i.cancelledAt_null);
    }

    // replacedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime >& v =
        o.replacedAt_;

      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_value (
        v,
        i.replacedAt_value,
        i.replacedAt_null);
    }

    // usedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime >& v =
        o.usedAt_;

      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_value (
        v,
        i.usedAt_value,
        i.usedAt_null);
    }

    // emailFailedAt_
    //
    {
      ::odb::nullable< ::boost::posix_time::ptime >& v =
        o.emailFailedAt_;

      pgsql::value_traits<
          ::odb::nullable< ::boost::posix_time::ptime >,
          pgsql::id_timestamp >::set_value (
        v,
        i.emailFailedAt_value,
        i.emailFailedAt_null);
    }

    // failureMessage_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.failureMessage_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_value (
        v,
        i.failureMessage_value,
        i.failureMessage_size,
        i.failureMessage_null);
    }
  }

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::persist_statement[] =
  "INSERT INTO \"password_reset_tokens\" "
  "(\"id\", "
  "\"user_id\", "
  "\"token_hash\", "
  "\"verification_code_hash\", "
  "\"verified_at\", "
  "\"expires_at\", "
  "\"created_at\", "
  "\"cancelled_at\", "
  "\"replaced_at\", "
  "\"used_at\", "
  "\"email_failed_at\", "
  "\"failure_message\") "
  "VALUES "
  "(DEFAULT, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) "
  "RETURNING \"id\"";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::find_statement[] =
  "SELECT "
  "\"password_reset_tokens\".\"id\", "
  "\"password_reset_tokens\".\"user_id\", "
  "\"password_reset_tokens\".\"token_hash\", "
  "\"password_reset_tokens\".\"verification_code_hash\", "
  "\"password_reset_tokens\".\"verified_at\", "
  "\"password_reset_tokens\".\"expires_at\", "
  "\"password_reset_tokens\".\"created_at\", "
  "\"password_reset_tokens\".\"cancelled_at\", "
  "\"password_reset_tokens\".\"replaced_at\", "
  "\"password_reset_tokens\".\"used_at\", "
  "\"password_reset_tokens\".\"email_failed_at\", "
  "\"password_reset_tokens\".\"failure_message\" "
  "FROM \"password_reset_tokens\" "
  "WHERE \"password_reset_tokens\".\"id\"=$1";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::update_statement[] =
  "UPDATE \"password_reset_tokens\" "
  "SET "
  "\"user_id\"=$1, "
  "\"token_hash\"=$2, "
  "\"verification_code_hash\"=$3, "
  "\"verified_at\"=$4, "
  "\"expires_at\"=$5, "
  "\"created_at\"=$6, "
  "\"cancelled_at\"=$7, "
  "\"replaced_at\"=$8, "
  "\"used_at\"=$9, "
  "\"email_failed_at\"=$10, "
  "\"failure_message\"=$11 "
  "WHERE \"id\"=$12";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::erase_statement[] =
  "DELETE FROM \"password_reset_tokens\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::query_statement[] =
  "SELECT "
  "\"password_reset_tokens\".\"id\", "
  "\"password_reset_tokens\".\"user_id\", "
  "\"password_reset_tokens\".\"token_hash\", "
  "\"password_reset_tokens\".\"verification_code_hash\", "
  "\"password_reset_tokens\".\"verified_at\", "
  "\"password_reset_tokens\".\"expires_at\", "
  "\"password_reset_tokens\".\"created_at\", "
  "\"password_reset_tokens\".\"cancelled_at\", "
  "\"password_reset_tokens\".\"replaced_at\", "
  "\"password_reset_tokens\".\"used_at\", "
  "\"password_reset_tokens\".\"email_failed_at\", "
  "\"password_reset_tokens\".\"failure_message\" "
  "FROM \"password_reset_tokens\"";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"password_reset_tokens\"";

  const char access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::table_name[] =
  "\"password_reset_tokens\"";

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.id_);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    ODB_POTENTIALLY_UNUSED (db);

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::pointer_type
  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.id_);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::object_type >
  access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::DbPasswordResetToken, id_pgsql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }

  // DbSchemaState
  //

  const char access::view_traits_impl< ::DbSchemaState, id_pgsql >::
  query_statement_name[] = "query_DbSchemaState";

  bool access::view_traits_impl< ::DbSchemaState, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // usersExists
    //
    t[0UL] = 0;

    // passwordResetTokensExists
    //
    t[1UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::DbSchemaState, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // usersExists
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.usersExists_value;
    b[n].is_null = &i.usersExists_null;
    n++;

    // passwordResetTokensExists
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.passwordResetTokensExists_value;
    b[n].is_null = &i.passwordResetTokensExists_null;
    n++;
  }

  void access::view_traits_impl< ::DbSchemaState, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // usersExists
    //
    {
      bool& v =
        o.usersExists;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.usersExists_value,
        i.usersExists_null);
    }

    // passwordResetTokensExists
    //
    {
      bool& v =
        o.passwordResetTokensExists;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.passwordResetTokensExists_value,
        i.passwordResetTokensExists_null);
    }
  }

  result< access::view_traits_impl< ::DbSchemaState, id_pgsql >::view_type >
  access::view_traits_impl< ::DbSchemaState, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // DbStringValue
  //

  const char access::view_traits_impl< ::DbStringValue, id_pgsql >::
  query_statement_name[] = "query_DbStringValue";

  bool access::view_traits_impl< ::DbStringValue, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // value
    //
    if (t[0UL])
    {
      i.value_value.capacity (i.value_size);
      grew = true;
    }

    return grew;
  }

  void access::view_traits_impl< ::DbStringValue, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // value
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.value_value.data ();
    b[n].capacity = i.value_value.capacity ();
    b[n].size = &i.value_size;
    b[n].is_null = &i.value_null;
    n++;
  }

  void access::view_traits_impl< ::DbStringValue, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      ::std::string& v =
        o.value;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.value_value,
        i.value_size,
        i.value_null);
    }
  }

  result< access::view_traits_impl< ::DbStringValue, id_pgsql >::view_type >
  access::view_traits_impl< ::DbStringValue, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // DbBoolValue
  //

  const char access::view_traits_impl< ::DbBoolValue, id_pgsql >::
  query_statement_name[] = "query_DbBoolValue";

  bool access::view_traits_impl< ::DbBoolValue, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // value
    //
    t[0UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::DbBoolValue, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // value
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.value_value;
    b[n].is_null = &i.value_null;
    n++;
  }

  void access::view_traits_impl< ::DbBoolValue, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // value
    //
    {
      bool& v =
        o.value;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.value_value,
        i.value_null);
    }
  }

  result< access::view_traits_impl< ::DbBoolValue, id_pgsql >::view_type >
  access::view_traits_impl< ::DbBoolValue, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // DbIdValue
  //

  const char access::view_traits_impl< ::DbIdValue, id_pgsql >::
  query_statement_name[] = "query_DbIdValue";

  bool access::view_traits_impl< ::DbIdValue, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::DbIdValue, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // id
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    n++;
  }

  void access::view_traits_impl< ::DbIdValue, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      long long unsigned int& v =
        o.id;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }
  }

  result< access::view_traits_impl< ::DbIdValue, id_pgsql >::view_type >
  access::view_traits_impl< ::DbIdValue, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // DbPasswordResetVerificationState
  //

  const char access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >::
  query_statement_name[] = "query_DbPasswordResetVerificationState";

  bool access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // alreadyVerified
    //
    t[1UL] = 0;

    // notExpired
    //
    t[2UL] = 0;

    // codeMatches
    //
    t[3UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // id
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    n++;

    // alreadyVerified
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.alreadyVerified_value;
    b[n].is_null = &i.alreadyVerified_null;
    n++;

    // notExpired
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.notExpired_value;
    b[n].is_null = &i.notExpired_null;
    n++;

    // codeMatches
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.codeMatches_value;
    b[n].is_null = &i.codeMatches_null;
    n++;
  }

  void access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      long long unsigned int& v =
        o.id;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // alreadyVerified
    //
    {
      bool& v =
        o.alreadyVerified;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.alreadyVerified_value,
        i.alreadyVerified_null);
    }

    // notExpired
    //
    {
      bool& v =
        o.notExpired;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.notExpired_value,
        i.notExpired_null);
    }

    // codeMatches
    //
    {
      bool& v =
        o.codeMatches;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.codeMatches_value,
        i.codeMatches_null);
    }
  }

  result< access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >::view_type >
  access::view_traits_impl< ::DbPasswordResetVerificationState, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }

  // DbPasswordResetUpdateState
  //

  const char access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >::
  query_statement_name[] = "query_DbPasswordResetUpdateState";

  bool access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id
    //
    t[0UL] = 0;

    // userId
    //
    t[1UL] = 0;

    // verified
    //
    t[2UL] = 0;

    return grew;
  }

  void access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i)
  {
    using namespace pgsql;

    pgsql::statement_kind sk (statement_select);
    ODB_POTENTIALLY_UNUSED (sk);

    std::size_t n (0);

    // id
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    n++;

    // userId
    //
    b[n].type = pgsql::bind::bigint;
    b[n].buffer = &i.userId_value;
    b[n].is_null = &i.userId_null;
    n++;

    // verified
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.verified_value;
    b[n].is_null = &i.verified_null;
    n++;
  }

  void access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >::
  init (view_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id
    //
    {
      long long unsigned int& v =
        o.id;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.id_value,
        i.id_null);
    }

    // userId
    //
    {
      long long unsigned int& v =
        o.userId;

      pgsql::value_traits<
          long long unsigned int,
          pgsql::id_bigint >::set_value (
        v,
        i.userId_value,
        i.userId_null);
    }

    // verified
    //
    {
      bool& v =
        o.verified;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.verified_value,
        i.verified_null);
    }
  }

  result< access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >::view_type >
  access::view_traits_impl< ::DbPasswordResetUpdateState, id_pgsql >::
  query (database&, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_view<view_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.image_binding ());

    if (im.version != sts.image_version () || imb.version == 0)
    {
      bind (imb.bind, im);
      sts.image_version (im.version);
      imb.version++;
    }

    const query_base_type& qs (q);
    qs.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        qs.clause (),
        false,
        true,
        qs.parameter_types (),
        qs.parameter_count (),
        qs.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::view_result_impl<view_type> > r (
      new (shared) pgsql::view_result_impl<view_type> (
        qs, st, sts, 0));

    return result<view_type> (r);
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"password_reset_tokens\" CASCADE");
          db.execute ("DROP TABLE IF EXISTS \"users\" CASCADE");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"users\" (\n"
                      "  \"id\" BIGSERIAL NOT NULL PRIMARY KEY,\n"
                      "  \"email\" TEXT NOT NULL CHECK (btrim(email) <> ''),\n"
                      "  \"password_hash\" TEXT NOT NULL CHECK (btrim(password_hash) <> ''),\n"
                      "  \"name\" TEXT NOT NULL CHECK (btrim(name) <> ''),\n"
                      "  \"login\" TEXT NOT NULL CHECK (btrim(login) <> ''))");
          db.execute ("CREATE UNIQUE INDEX \"users_email_i\"\n"
                      "  ON \"users\" (\"email\")");
          db.execute ("CREATE UNIQUE INDEX \"users_login_i\"\n"
                      "  ON \"users\" (\"login\")");
          db.execute ("CREATE TABLE \"password_reset_tokens\" (\n"
                      "  \"id\" BIGSERIAL NOT NULL PRIMARY KEY,\n"
                      "  \"user_id\" BIGINT NOT NULL REFERENCES \"users\" (\"id\") ON DELETE CASCADE,\n"
                      "  \"token_hash\" TEXT NOT NULL CHECK (btrim(token_hash) <> ''),\n"
                      "  \"verification_code_hash\" TEXT NOT NULL CHECK (btrim(verification_code_hash) <> ''),\n"
                      "  \"verified_at\" TIMESTAMP NULL,\n"
                      "  \"expires_at\" TIMESTAMP NULL,\n"
                      "  \"created_at\" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,\n"
                      "  \"cancelled_at\" TIMESTAMP NULL,\n"
                      "  \"replaced_at\" TIMESTAMP NULL,\n"
                      "  \"used_at\" TIMESTAMP NULL,\n"
                      "  \"email_failed_at\" TIMESTAMP NULL,\n"
                      "  \"failure_message\" TEXT NULL)");
          db.execute ("CREATE UNIQUE INDEX \"password_reset_tokens_token_hash_i\"\n"
                      "  ON \"password_reset_tokens\" (\"token_hash\")");
          db.execute ("CREATE UNIQUE INDEX \"password_reset_tokens_one_active_per_user\"\n"
                      "  ON \"password_reset_tokens\" (\"user_id\")\n"
                      " WHERE cancelled_at IS NULL AND replaced_at IS NULL AND used_at IS NULL AND email_failed_at IS NULL");
          db.execute ("CREATE INDEX \"password_reset_tokens_user_id_created_at_idx\"\n"
                      "  ON \"password_reset_tokens\" (\n"
                      "    \"user_id\",\n"
                      "    \"created_at\" DESC)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_pgsql,
    "",
    &create_schema);
}

#include <odb/post.hxx>
